{
  "uid" : "a0a549961b8a094a",
  "name" : "test_select_nan",
  "fullName" : "tests.integration.dbapi.async.V2.test_queries_async#test_select_nan",
  "historyId" : "d38be4a2fa9309f5448267f4cf157d31",
  "time" : {
    "start" : 1714662871584,
    "stop" : 1714662874000,
    "duration" : 2416
  },
  "status" : "broken",
  "statusMessage" : "exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)",
  "statusTrace" : "+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 954, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/integration/dbapi/async/V2/test_queries_async.py\", line 118, in test_select_nan\n    |     await c.execute(\"SELECT 'nan'::float, '-nan'::float\")\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/cursor.py\", line 286, in execute\n    |     await self._do_execute(query, params_list, skip_parsing, async_execution)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/cursor.py\", line 233, in _do_execute\n    |     await self._raise_if_error(resp)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/cursor.py\", line 124, in _raise_if_error\n    |     resp.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_models.py\", line 749, in raise_for_status\n    |     raise HTTPStatusError(message, request=request, response=self)\n    | httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://integration-testing-1714662662834.01h6xa49e5dxdz4tm0qc9mk7cz.us-east-1.staging.firebolt.io/?database=integration_testing__1714662662834&output_format=JSON_Compact'\n    | For more information check: https://httpstatuses.com/502\n    +------------------------------------",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "auth",
    "time" : {
      "start" : 1714662868366,
      "stop" : 1714662868535,
      "duration" : 169
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "api_endpoint",
    "time" : {
      "start" : 1714662868535,
      "stop" : 1714662868535,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "engine_name",
    "time" : {
      "start" : 1714662871583,
      "stop" : 1714662871584,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "account_name",
    "time" : {
      "start" : 1714662868535,
      "stop" : 1714662868535,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "service_secret",
    "time" : {
      "start" : 1714662868366,
      "stop" : 1714662868366,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "database_name",
    "time" : {
      "start" : 1714662868366,
      "stop" : 1714662868366,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "connection",
    "time" : {
      "start" : 1714662871584,
      "stop" : 1714662871584,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "service_id",
    "time" : {
      "start" : 1714662868366,
      "stop" : 1714662868366,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)",
    "statusTrace" : "+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 954, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/integration/dbapi/async/V2/test_queries_async.py\", line 118, in test_select_nan\n    |     await c.execute(\"SELECT 'nan'::float, '-nan'::float\")\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/cursor.py\", line 286, in execute\n    |     await self._do_execute(query, params_list, skip_parsing, async_execution)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/cursor.py\", line 233, in _do_execute\n    |     await self._raise_if_error(resp)\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/firebolt/async_db/cursor.py\", line 124, in _raise_if_error\n    |     resp.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_models.py\", line 749, in raise_for_status\n    |     raise HTTPStatusError(message, request=request, response=self)\n    | httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://integration-testing-1714662662834.01h6xa49e5dxdz4tm0qc9mk7cz.us-east-1.staging.firebolt.io/?database=integration_testing__1714662662834&output_format=JSON_Compact'\n    | For more information check: https://httpstatuses.com/502\n    +------------------------------------",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "6f8d47b5999ac119",
      "name" : "log",
      "source" : "6f8d47b5999ac119.txt",
      "type" : "text/plain",
      "size" : 183
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "trio(run=<function run at 0x7f5b789e19d0>)"
  }, {
    "name" : "parentSuite",
    "value" : "tests.integration.dbapi.async.V2"
  }, {
    "name" : "suite",
    "value" : "test_queries_async"
  }, {
    "name" : "host",
    "value" : "fv-az1247-807"
  }, {
    "name" : "thread",
    "value" : "2484-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.integration.dbapi.async.V2.test_queries_async"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "trio(run=<function run at 0x7f5b789e19d0>)" ]
  },
  "source" : "a0a549961b8a094a.json",
  "parameterValues" : [ ]
}