{"uid":"5f5b448a4a28a310","name":"test_true_concurent_requests","fullName":"tests.unit.V1.client.test_client_async#test_true_concurent_requests","historyId":"235d6b8865fc62b089a4a871e01b6091","time":{"start":1731553766649,"stop":1731553766928,"duration":279},"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/unit/conftest.py\", line 247, in wrapper\n    |     await func(*args, **kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/unit/V1/client/test_client_async.py\", line 213, in test_true_concurent_requests\n    |     for url in urls:\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n    |     raise combined_error_from_nursery\n    | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (10 sub-exceptions)\n    +-+---------------- 1 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1663, in _send_handling_auth\n      |     raise exc\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1652, in _send_handling_auth\n      |     next_request = await auth_flow.asend(response)\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 174, in async_auth_flow\n      |     if self._lock.locked() and self._lock._owner_task == get_current_task():\n      | AttributeError: 'Lock' object has no attribute '_owner_task'\n      +---------------- 2 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 3 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 4 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 5 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 6 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 7 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 8 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 9 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +---------------- 10 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3625f584a0>\n      +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"global_fake_fs","time":{"start":1731553766641,"stop":1731553766647,"duration":6},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_cache","time":{"start":1731553766641,"stop":1731553766641,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"global_fake_fs::0","time":{"start":1731553766952,"stop":1731553766953,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"trio(run=<function run at 0x7f3628a02160>)"},{"name":"parentSuite","value":"tests.unit.V1.client"},{"name":"suite","value":"test_client_async"},{"name":"host","value":"fv-az2021-220"},{"name":"thread","value":"2157-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.unit.V1.client.test_client_async"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":110,"skipped":0,"passed":22,"unknown":0,"total":132},"items":[{"uid":"a1fff8d7295c770d","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/358//#testresult/a1fff8d7295c770d","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731553632202,"stop":1731553632443,"duration":241}},{"uid":"aec9c12341a7b7b3","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/354//#testresult/aec9c12341a7b7b3","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731467332632,"stop":1731467332824,"duration":192}},{"uid":"1ce81506697a7162","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/357//#testresult/1ce81506697a7162","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731467187493,"stop":1731467187747,"duration":254}},{"uid":"4fcbe05dabd1421a","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/353//#testresult/4fcbe05dabd1421a","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731380832958,"stop":1731380833238,"duration":280}},{"uid":"6177b20d73257986","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/356//#testresult/6177b20d73257986","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731380692284,"stop":1731380692559,"duration":275}},{"uid":"1a2932986f7220cb","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/352//#testresult/1a2932986f7220cb","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731294586674,"stop":1731294586933,"duration":259}},{"uid":"4bfbd9fb9443bbd2","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/355//#testresult/4bfbd9fb9443bbd2","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731294435029,"stop":1731294435222,"duration":193}},{"uid":"22e4a81bf600600f","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/351//#testresult/22e4a81bf600600f","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731208182810,"stop":1731208182984,"duration":174}},{"uid":"9743606fdf2e193d","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/354//#testresult/9743606fdf2e193d","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731208053927,"stop":1731208054181,"duration":254}},{"uid":"fad08de2017afd0","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/350//#testresult/fad08de2017afd0","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731121927666,"stop":1731121927885,"duration":219}},{"uid":"fa2e14dc1b230b33","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/353//#testresult/fa2e14dc1b230b33","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731121539557,"stop":1731121539773,"duration":216}},{"uid":"c0287aee783bde7e","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/349//#testresult/c0287aee783bde7e","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731035295739,"stop":1731035295989,"duration":250}},{"uid":"44e6ac8abd2d7213","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/352//#testresult/44e6ac8abd2d7213","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731035154178,"stop":1731035154393,"duration":215}},{"uid":"1a54951f8c73af3b","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/348//#testresult/1a54951f8c73af3b","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730948979703,"stop":1730948979913,"duration":210}},{"uid":"ac6edcc9b5ddc58f","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/351//#testresult/ac6edcc9b5ddc58f","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730948850688,"stop":1730948850929,"duration":241}},{"uid":"7584165571c988c4","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/347//#testresult/7584165571c988c4","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730862471711,"stop":1730862471965,"duration":254}},{"uid":"209e92d4bca1c599","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/350//#testresult/209e92d4bca1c599","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730862306611,"stop":1730862306799,"duration":188}},{"uid":"178769512a94d042","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/346//#testresult/178769512a94d042","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730776105197,"stop":1730776105452,"duration":255}},{"uid":"7738fb4d4c8aa9d4","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/349//#testresult/7738fb4d4c8aa9d4","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730775937312,"stop":1730775937483,"duration":171}},{"uid":"697901ce94f80b73","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/345//#testresult/697901ce94f80b73","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730690001292,"stop":1730690001508,"duration":216}}]},"tags":["trio(run=<function run at 0x7f3628a02160>)"]},"source":"5f5b448a4a28a310.json","parameterValues":[]}