{"uid":"455025920b7048b2","name":"test_concurent_auth_lock","fullName":"tests.unit.client.test_client_async#test_concurent_auth_lock","historyId":"7d946e1b5685738953e603f5812157c0","time":{"start":1729739282301,"stop":1729739282423,"duration":122},"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/unit/client/test_client_async.py\", line 138, in test_concurent_auth_lock\n    |     for url in urls:\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n    |     raise combined_error_from_nursery\n    | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (10 sub-exceptions)\n    +-+---------------- 1 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1663, in _send_handling_auth\n      |     raise exc\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1652, in _send_handling_auth\n      |     next_request = await auth_flow.asend(response)\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 174, in async_auth_flow\n      |     if self._lock.locked() and self._lock._owner_task == get_current_task():\n      | AttributeError: 'Lock' object has no attribute '_owner_task'\n      +---------------- 2 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 3 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 4 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 5 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 6 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 7 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 8 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 9 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +---------------- 10 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fbeaa4da7c0>\n      +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"clear_cache","time":{"start":1729739282294,"stop":1729739282295,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"global_fake_fs","time":{"start":1729739282295,"stop":1729739282299,"duration":4},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"global_fake_fs::0","time":{"start":1729739282445,"stop":1729739282446,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"trio(run=<function run at 0x7fbead5cd1f0>)"},{"name":"parentSuite","value":"tests.unit.client"},{"name":"suite","value":"test_client_async"},{"name":"host","value":"fv-az985-968"},{"name":"thread","value":"2071-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.unit.client.test_client_async"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":67,"skipped":0,"passed":22,"unknown":0,"total":89},"items":[{"uid":"5b0c2e36b64b9c1f","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/333//#testresult/5b0c2e36b64b9c1f","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729653040314,"stop":1729653040436,"duration":122}},{"uid":"b88827e5aafd2933","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/336//#testresult/b88827e5aafd2933","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729652898622,"stop":1729652898745,"duration":123}},{"uid":"833ae4966218926c","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/332//#testresult/833ae4966218926c","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729566691840,"stop":1729566691963,"duration":123}},{"uid":"e54e716439ad4e8e","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/335//#testresult/e54e716439ad4e8e","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729566555724,"stop":1729566555847,"duration":123}},{"uid":"4aaa6da4ac5a8ac0","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/331//#testresult/4aaa6da4ac5a8ac0","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729480402486,"stop":1729480402603,"duration":117}},{"uid":"1a6bbf5c35bfa484","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/334//#testresult/1a6bbf5c35bfa484","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729480273685,"stop":1729480273808,"duration":123}},{"uid":"664282135421b92","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/330//#testresult/664282135421b92","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729394048724,"stop":1729394048849,"duration":125}},{"uid":"806487fea8753515","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/333//#testresult/806487fea8753515","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729393913276,"stop":1729393913399,"duration":123}},{"uid":"74ad30c5f8069ffd","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/329//#testresult/74ad30c5f8069ffd","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729307383618,"stop":1729307383741,"duration":123}},{"uid":"69c1634d7242e296","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/332//#testresult/69c1634d7242e296","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729307260621,"stop":1729307260747,"duration":126}},{"uid":"da3d1e15dafa035f","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/328//#testresult/da3d1e15dafa035f","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729221085195,"stop":1729221085319,"duration":124}},{"uid":"60de162985984c0a","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/331//#testresult/60de162985984c0a","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729220938883,"stop":1729220939008,"duration":125}},{"uid":"91c76408857bb984","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/327//#testresult/91c76408857bb984","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729134634732,"stop":1729134634856,"duration":124}},{"uid":"d5e4048ea7dfc2a9","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/330//#testresult/d5e4048ea7dfc2a9","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729134498407,"stop":1729134498530,"duration":123}},{"uid":"2b2a49f8ce2c53f9","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/326//#testresult/2b2a49f8ce2c53f9","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729048355046,"stop":1729048355163,"duration":117}},{"uid":"e84ed54b49f5cac6","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/329//#testresult/e84ed54b49f5cac6","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1729048202713,"stop":1729048202827,"duration":114}},{"uid":"b3a78aaa8cd38d5c","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/325//#testresult/b3a78aaa8cd38d5c","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1728961898674,"stop":1728961898791,"duration":117}},{"uid":"990def375defd9e3","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/328//#testresult/990def375defd9e3","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1728961757400,"stop":1728961757516,"duration":116}},{"uid":"2629ef5134d35561","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/324//#testresult/2629ef5134d35561","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1728875605841,"stop":1728875605956,"duration":115}},{"uid":"383e784332025a48","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/327//#testresult/383e784332025a48","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1728875450735,"stop":1728875450850,"duration":115}}]},"tags":["trio(run=<function run at 0x7fbead5cd1f0>)"]},"source":"455025920b7048b2.json","parameterValues":[]}